### ISSUE TITLE
[bug] Default _9999-custom-settings.py causes ImportError

### ISSUE THREAD

**Issue by fzakfeld** [osism/issues#1172]
### OSISM release version

8.0.2

### What's the problem?

[In https://github.com/osism/cfg-cookiecutter/blob/main/%7B%7Bcookiecutter.project_name%7D%7D/environments/kolla/files/overlays/horizon/_9999-custom-settings.py](https://github.com/osism/cfg-cookiecutter/blob/main/%7B%7Bcookiecutter.project_name%7D%7D/environments/kolla/files/overlays/horizon/_9999-custom-settings.py) contains `from django.utils.translation import ugettext_lazy as _` which will not work with the horizon container in 8.0.2. The container will start but there will be the following error in the log:

```
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/var/lib/kolla/venv/lib/python3.10/site-packages/django/utils/translation/init.py)
```

We don't use translation in the custom settings file, so I just removed it without further investigations. This should be fixed in the cookiecutter template and the fix should be in the docs as well for existing setups.

### References to existing reports

References to existing bug reports, mailing lists, ...

### Severity

low

### Urgency

low
